Repository Steinbeck-Lab/cheminformatics-microservice, pull requests merged in 2023-04, with the labels that each got.

#98 chore(main): release 0.7.1
  CHANGELOG.md
Labels: autorelease: pending

#110 chore(main): release 0.7.2
  CHANGELOG.md
Labels: autorelease: pending

#126 fix: Naming conventions and descriptions. Fixes: #121,#122 and #123
  app/routers/chem.py
  app/routers/converters.py
  app/routers/decimer.py
Labels: bug

#128 feat: return standardized SMILES with more info as distionary, minor …
  app/routers/chem.py
  app/routers/decimer.py
Labels: bug, enhancement

#130 feat: Add npscore and depict tests
  app/modules/depict.py
  tests/test_functions.py
Labels: enhancement

#132 feat: Add display Tanimoto similarity matrix #131
  app/modules/alldescriptors.py
  app/modules/cdkmodules.py
  app/modules/rdkitmodules.py
  app/routers/chem.py
Labels: enhancement

#125 Development
  app/modules/alldescriptors.py
  app/modules/cdkmodules.py
  app/modules/depict.py
  app/modules/rdkitmodules.py
  app/routers/chem.py
  app/routers/converters.py
  app/routers/decimer.py
  tests/test_functions.py
Labels: bug, enhancement

#134 chore(main): release 0.8.0
  CHANGELOG.md
Labels: autorelease: pending
