Repository Steinbeck-Lab/cheminformatics-microservice, pull requests merged in 2023-03, with the labels that each got.

#12 feat: Added support for CDK SDG 2D coordinates
  app/modules/cdkmodules.py
  app/modules/classyfire.py
  app/routers/chem.py
Labels: enhancement

#34 feat: add converters and decimer modules
  README.md
  app/routers/chem.py
  app/routers/converters.py
  app/routers/decimer.py
Labels: enhancement

#58 feat: add SRU, Murko framework and implement COCONUT related descriptors
  app/modules/cdkmodules.py
  app/modules/coconutdescriptors.py
  app/modules/rdkitmodules.py
  app/routers/chem.py
Labels: enhancement

#71 fix: Mol block display issue
  app/routers/converters.py
Labels: bug

#69 chore(main): release 0.5.2
  CHANGELOG.md
Labels: autorelease: pending

#83 feat: Descriptor related additions
  app/modules/alldescriptors.py
  app/modules/cdkmodules.py
  app/modules/coconutdescriptors.py
  app/modules/rdkitmodules.py
  app/routers/chem.py
  app/templates/style.css
  requirements.txt
Labels: enhancement

#87 chore(main): release 0.6.0
  CHANGELOG.md
Labels: autorelease: pending

#93 fix: display CDK aromatic ring descriptor
  app/modules/alldescriptors.py
Labels: bug

#94 chore(main): release 0.7.0
  CHANGELOG.md
Labels: autorelease: pending

#97 fix: display float/int instead of str/array #95
  app/modules/alldescriptors.py
  app/modules/cdkmodules.py
  app/modules/coconutdescriptors.py
  app/modules/rdkitmodules.py
  app/routers/chem.py
Labels: bug

#99 fix: reduce import RDKit 3D coordinate generation
  app/modules/rdkitmodules.py
  app/routers/converters.py
Labels: enhancement
