Repository Steinbeck-Lab/cheminformatics-microservice, pull requests merged in 2023-06, with the labels that each got.

#157 feat: Add CXSMILES conversion with CDK #156
  app/modules/cdkmodules.py
  app/routers/converters.py
Labels: enhancement

#152 New Developments
  Dockerfile
  README.md
  app/__init__.py
  app/config.py
  app/main.py
  app/modules/alldescriptors.py
  app/modules/cdkmodules.py
  app/modules/coconutpreprocess.py
  app/modules/depict.py
  app/modules/rdkitmodules.py
  app/routers/chem.py
  app/routers/converters.py
  app/routers/decimer.py
  public/img/logo.png
  public/img/logo.svg
  requirements.txt
Labels: enhancement, testing

#164 feat: Add minimal logos
  public/img/logo_small.png
  public/img/logo_small_inverted.png
Labels: enhancement

#161 chore(main): release 0.9.0
  CHANGELOG.md
Labels: autorelease: pending

#168 docs: Introduction added
  .gitignore
  docs/.vitepress/cache/deps/_metadata.json
  docs/introduction.md
  docs/public/logo_big.png
Labels: documentation

#174 feat: Add converter tests #173
  app/routers/converters.py
  tests/test_converters.py
Labels: testing

#183 feat: Add tests for chem router #181
  tests/test_chem.py
  tests/test_converters.py
Labels: testing

#217 chore(main): release 0.11.0
  CHANGELOG.md
Labels: autorelease: pending

#226 chore(main): release 0.11.1
  CHANGELOG.md
Labels: autorelease: pending

#241 chore(main): release 0.12.0
  CHANGELOG.md
Labels: autorelease: pending
