Repository Steinbeck-Lab/cheminformatics-microservice, pull requests merged in 2023-09, with the labels that each got.

#369 wip: handling invalid input in a consistent and logical way
  app/exception_handlers.py
  app/main.py
  app/modules/all_descriptors.py
  app/modules/classyfire.py
  app/modules/coconut/descriptors.py
  app/modules/coconut/preprocess.py
  app/modules/depiction.py
  app/modules/npscorer.py
  app/modules/toolkits/cdk_wrapper.py
  app/modules/toolkits/helpers.py
  app/modules/toolkits/rdkit_wrapper.py
  app/modules/tools/sugar_removal.py
  app/routers/chem.py
  app/routers/converters.py
  app/routers/depict.py
  app/routers/ocsr.py
  app/routers/tools.py
  tests/test_functions.py
Labels: wip

#370 Development
  .github/workflows/dev-build.yml
  .github/workflows/prod-build.yml
  .github/workflows/test-check.yml
  CHANGELOG.md
  CITATION.cff
  README.md
  app/__init__.py
  app/exception_handlers.py
  app/main.py
  app/modules/all_descriptors.py
  app/modules/classyfire.py
  app/modules/coconut/descriptors.py
  app/modules/coconut/preprocess.py
  app/modules/decimer.py
  app/modules/depiction.py
  app/modules/npscorer.py
  app/modules/toolkits/cdk_wrapper.py
  app/modules/toolkits/helpers.py
  app/modules/toolkits/openbabel_wrapper.py
  app/modules/toolkits/rdkit_wrapper.py
  app/modules/tools/sugar_removal.py
  app/modules/tools/surge.py
  app/routers/chem.py
  app/routers/compose.py
  app/routers/converters.py
  app/routers/depict.py
  app/routers/ocsr.py
  app/routers/tools.py
  app/schemas/chemblstandardizer.py
  cpm-dashboard.json
  docker-compose.yml
  docs/.vitepress/config.ts
  docs/architecture.md
  docs/cluster-deployment.md
  docs/conf.py
  docs/contributors.md
  docs/docker.md
  docs/index.md
  docs/index.rst
  docs/installation.md
  docs/introduction.md
  docs/issues.md
  docs/modules.rst
  docs/public/logo_big.png
  docs/standalone.md
  docs/versions.md
  ops/docker-compose-dev.yml
  ops/docker-compose-prod.yml
  ops/zero-downtime-deploy-bash-script.sh
  package-lock.json
  prometheus_data/prometheus.yml
  public/img/logo.png
  public/img/logo.svg
  tests/test_chem.py
  tests/test_converters.py
  tests/test_depict.py
  tests/test_functions.py
  tests/test_ocsr.py
  tests/test_tools.py
Labels: testing

#317 chore(main): release 1.4.0
  CHANGELOG.md
Labels: autorelease: pending, wip

#397 chore(main): release 1.5.0
  CHANGELOG.md
Labels: autorelease: pending

#400 chore(main): release 1.6.0
  CHANGELOG.md
Labels: autorelease: pending
